apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-code-generator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-code-generator
  template:
    metadata:
      labels:
        app: ai-code-generator
    spec:
      containers:
      - name: ai-code-generator
        image: bulent1234/ai-code-generator:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ai-code-generator-service
spec:
  selector:
    app: ai-code-generator
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 5000
  type: LoadBalancer
